name: example
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: 5.1.0
  camera:
  numberpicker: ^2.0.1
  idntify_widget:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 uses-material-design: true
